[package]
name = "radicle-cob"
version = "0.1.0"
authors = [
  "Alex Good <alex@memoryandthought.me>",
  "Fintan Halpenny <fintan.halpenny@gmail.com>",
]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Library for implementing Radicle Collaborative Objects"
keywords = ["radicle", "collaborative objects", "cob", "cobs"]

[lib]

[dependencies]
fastrand = { version = "1.9.0" }
log = { version = "0.4.17" }
nonempty = { version = "0.8.1", features = ["serialize"] }
radicle-git-ext = { version = "0.6.0", features = ["serde"] }
serde_json = { version = "1.0" }
thiserror = { version = "1.0" }

[dependencies.git2]
version = "0.17.0"
default-features = false
features = ["vendored-libgit2"]

[dependencies.radicle-crypto]
path = "../radicle-crypto"
version = "0.1"
features = ["ssh"]

[dependencies.radicle-dag]
path = "../radicle-dag"
version = "0.1"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dev-dependencies]
fastrand = { version = "1.9.0", default-features = false }
tempfile = { version = "3" }
qcheck = { version = "1", default-features = false }
qcheck-macros = { version = "1", default-features = false }

[dev-dependencies.radicle-crypto]
path = "../radicle-crypto"
version = "0.1"
features = ["test"]
